package com.icday.database.automatic.entitys;

import java.util.Date;

public class TbItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item.insid
     *
     * @mbggenerated
     */
    private String insid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item.cfgid
     *
     * @mbggenerated
     */
    private String cfgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item.params
     *
     * @mbggenerated
     */
    private String params;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_item.insid
     *
     * @return the value of tb_item.insid
     *
     * @mbggenerated
     */
    public String getInsid() {
        return insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_item.insid
     *
     * @param insid the value for tb_item.insid
     *
     * @mbggenerated
     */
    public void setInsid(String insid) {
        this.insid = insid == null ? null : insid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_item.type
     *
     * @return the value of tb_item.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_item.type
     *
     * @param type the value for tb_item.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_item.cfgid
     *
     * @return the value of tb_item.cfgid
     *
     * @mbggenerated
     */
    public String getCfgid() {
        return cfgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_item.cfgid
     *
     * @param cfgid the value for tb_item.cfgid
     *
     * @mbggenerated
     */
    public void setCfgid(String cfgid) {
        this.cfgid = cfgid == null ? null : cfgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_item.createtime
     *
     * @return the value of tb_item.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_item.createtime
     *
     * @param createtime the value for tb_item.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_item.params
     *
     * @return the value of tb_item.params
     *
     * @mbggenerated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_item.params
     *
     * @param params the value for tb_item.params
     *
     * @mbggenerated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }
}