package com.icday.database.automatic.entitys;

public class TbNpc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_npc.insid
     *
     * @mbggenerated
     */
    private String insid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_npc.cfgid
     *
     * @mbggenerated
     */
    private String cfgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_npc.insid
     *
     * @return the value of tb_npc.insid
     *
     * @mbggenerated
     */
    public String getInsid() {
        return insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_npc.insid
     *
     * @param insid the value for tb_npc.insid
     *
     * @mbggenerated
     */
    public void setInsid(String insid) {
        this.insid = insid == null ? null : insid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_npc.cfgid
     *
     * @return the value of tb_npc.cfgid
     *
     * @mbggenerated
     */
    public String getCfgid() {
        return cfgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_npc.cfgid
     *
     * @param cfgid the value for tb_npc.cfgid
     *
     * @mbggenerated
     */
    public void setCfgid(String cfgid) {
        this.cfgid = cfgid == null ? null : cfgid.trim();
    }
}