package com.icday.database.automatic.entitys;

public class TbPack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pack.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pack.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pack.openlength
     *
     * @mbggenerated
     */
    private Integer openlength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pack.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pack.userid
     *
     * @return the value of tb_pack.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pack.userid
     *
     * @param userid the value for tb_pack.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pack.type
     *
     * @return the value of tb_pack.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pack.type
     *
     * @param type the value for tb_pack.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pack.openlength
     *
     * @return the value of tb_pack.openlength
     *
     * @mbggenerated
     */
    public Integer getOpenlength() {
        return openlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pack.openlength
     *
     * @param openlength the value for tb_pack.openlength
     *
     * @mbggenerated
     */
    public void setOpenlength(Integer openlength) {
        this.openlength = openlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pack.content
     *
     * @return the value of tb_pack.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pack.content
     *
     * @param content the value for tb_pack.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}