package com.icday.database.automatic.entitys;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbRoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    public TbRoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInsidIsNull() {
            addCriterion("insId is null");
            return (Criteria) this;
        }

        public Criteria andInsidIsNotNull() {
            addCriterion("insId is not null");
            return (Criteria) this;
        }

        public Criteria andInsidEqualTo(String value) {
            addCriterion("insId =", value, "insid");
            return (Criteria) this;
        }

        public Criteria andInsidNotEqualTo(String value) {
            addCriterion("insId <>", value, "insid");
            return (Criteria) this;
        }

        public Criteria andInsidGreaterThan(String value) {
            addCriterion("insId >", value, "insid");
            return (Criteria) this;
        }

        public Criteria andInsidGreaterThanOrEqualTo(String value) {
            addCriterion("insId >=", value, "insid");
            return (Criteria) this;
        }

        public Criteria andInsidLessThan(String value) {
            addCriterion("insId <", value, "insid");
            return (Criteria) this;
        }

        public Criteria andInsidLessThanOrEqualTo(String value) {
            addCriterion("insId <=", value, "insid");
            return (Criteria) this;
        }

        public Criteria andInsidLike(String value) {
            addCriterion("insId like", value, "insid");
            return (Criteria) this;
        }

        public Criteria andInsidNotLike(String value) {
            addCriterion("insId not like", value, "insid");
            return (Criteria) this;
        }

        public Criteria andInsidIn(List<String> values) {
            addCriterion("insId in", values, "insid");
            return (Criteria) this;
        }

        public Criteria andInsidNotIn(List<String> values) {
            addCriterion("insId not in", values, "insid");
            return (Criteria) this;
        }

        public Criteria andInsidBetween(String value1, String value2) {
            addCriterion("insId between", value1, value2, "insid");
            return (Criteria) this;
        }

        public Criteria andInsidNotBetween(String value1, String value2) {
            addCriterion("insId not between", value1, value2, "insid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCfgidIsNull() {
            addCriterion("cfgid is null");
            return (Criteria) this;
        }

        public Criteria andCfgidIsNotNull() {
            addCriterion("cfgid is not null");
            return (Criteria) this;
        }

        public Criteria andCfgidEqualTo(String value) {
            addCriterion("cfgid =", value, "cfgid");
            return (Criteria) this;
        }

        public Criteria andCfgidNotEqualTo(String value) {
            addCriterion("cfgid <>", value, "cfgid");
            return (Criteria) this;
        }

        public Criteria andCfgidGreaterThan(String value) {
            addCriterion("cfgid >", value, "cfgid");
            return (Criteria) this;
        }

        public Criteria andCfgidGreaterThanOrEqualTo(String value) {
            addCriterion("cfgid >=", value, "cfgid");
            return (Criteria) this;
        }

        public Criteria andCfgidLessThan(String value) {
            addCriterion("cfgid <", value, "cfgid");
            return (Criteria) this;
        }

        public Criteria andCfgidLessThanOrEqualTo(String value) {
            addCriterion("cfgid <=", value, "cfgid");
            return (Criteria) this;
        }

        public Criteria andCfgidLike(String value) {
            addCriterion("cfgid like", value, "cfgid");
            return (Criteria) this;
        }

        public Criteria andCfgidNotLike(String value) {
            addCriterion("cfgid not like", value, "cfgid");
            return (Criteria) this;
        }

        public Criteria andCfgidIn(List<String> values) {
            addCriterion("cfgid in", values, "cfgid");
            return (Criteria) this;
        }

        public Criteria andCfgidNotIn(List<String> values) {
            addCriterion("cfgid not in", values, "cfgid");
            return (Criteria) this;
        }

        public Criteria andCfgidBetween(String value1, String value2) {
            addCriterion("cfgid between", value1, value2, "cfgid");
            return (Criteria) this;
        }

        public Criteria andCfgidNotBetween(String value1, String value2) {
            addCriterion("cfgid not between", value1, value2, "cfgid");
            return (Criteria) this;
        }

        public Criteria andMapIsNull() {
            addCriterion("map is null");
            return (Criteria) this;
        }

        public Criteria andMapIsNotNull() {
            addCriterion("map is not null");
            return (Criteria) this;
        }

        public Criteria andMapEqualTo(Integer value) {
            addCriterion("map =", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapNotEqualTo(Integer value) {
            addCriterion("map <>", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapGreaterThan(Integer value) {
            addCriterion("map >", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapGreaterThanOrEqualTo(Integer value) {
            addCriterion("map >=", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapLessThan(Integer value) {
            addCriterion("map <", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapLessThanOrEqualTo(Integer value) {
            addCriterion("map <=", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapIn(List<Integer> values) {
            addCriterion("map in", values, "map");
            return (Criteria) this;
        }

        public Criteria andMapNotIn(List<Integer> values) {
            addCriterion("map not in", values, "map");
            return (Criteria) this;
        }

        public Criteria andMapBetween(Integer value1, Integer value2) {
            addCriterion("map between", value1, value2, "map");
            return (Criteria) this;
        }

        public Criteria andMapNotBetween(Integer value1, Integer value2) {
            addCriterion("map not between", value1, value2, "map");
            return (Criteria) this;
        }

        public Criteria andPosxIsNull() {
            addCriterion("posX is null");
            return (Criteria) this;
        }

        public Criteria andPosxIsNotNull() {
            addCriterion("posX is not null");
            return (Criteria) this;
        }

        public Criteria andPosxEqualTo(Double value) {
            addCriterion("posX =", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxNotEqualTo(Double value) {
            addCriterion("posX <>", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxGreaterThan(Double value) {
            addCriterion("posX >", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxGreaterThanOrEqualTo(Double value) {
            addCriterion("posX >=", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxLessThan(Double value) {
            addCriterion("posX <", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxLessThanOrEqualTo(Double value) {
            addCriterion("posX <=", value, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxIn(List<Double> values) {
            addCriterion("posX in", values, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxNotIn(List<Double> values) {
            addCriterion("posX not in", values, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxBetween(Double value1, Double value2) {
            addCriterion("posX between", value1, value2, "posx");
            return (Criteria) this;
        }

        public Criteria andPosxNotBetween(Double value1, Double value2) {
            addCriterion("posX not between", value1, value2, "posx");
            return (Criteria) this;
        }

        public Criteria andPosyIsNull() {
            addCriterion("posY is null");
            return (Criteria) this;
        }

        public Criteria andPosyIsNotNull() {
            addCriterion("posY is not null");
            return (Criteria) this;
        }

        public Criteria andPosyEqualTo(Double value) {
            addCriterion("posY =", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyNotEqualTo(Double value) {
            addCriterion("posY <>", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyGreaterThan(Double value) {
            addCriterion("posY >", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyGreaterThanOrEqualTo(Double value) {
            addCriterion("posY >=", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyLessThan(Double value) {
            addCriterion("posY <", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyLessThanOrEqualTo(Double value) {
            addCriterion("posY <=", value, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyIn(List<Double> values) {
            addCriterion("posY in", values, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyNotIn(List<Double> values) {
            addCriterion("posY not in", values, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyBetween(Double value1, Double value2) {
            addCriterion("posY between", value1, value2, "posy");
            return (Criteria) this;
        }

        public Criteria andPosyNotBetween(Double value1, Double value2) {
            addCriterion("posY not between", value1, value2, "posy");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andAdultIsNull() {
            addCriterion("adult is null");
            return (Criteria) this;
        }

        public Criteria andAdultIsNotNull() {
            addCriterion("adult is not null");
            return (Criteria) this;
        }

        public Criteria andAdultEqualTo(Byte value) {
            addCriterion("adult =", value, "adult");
            return (Criteria) this;
        }

        public Criteria andAdultNotEqualTo(Byte value) {
            addCriterion("adult <>", value, "adult");
            return (Criteria) this;
        }

        public Criteria andAdultGreaterThan(Byte value) {
            addCriterion("adult >", value, "adult");
            return (Criteria) this;
        }

        public Criteria andAdultGreaterThanOrEqualTo(Byte value) {
            addCriterion("adult >=", value, "adult");
            return (Criteria) this;
        }

        public Criteria andAdultLessThan(Byte value) {
            addCriterion("adult <", value, "adult");
            return (Criteria) this;
        }

        public Criteria andAdultLessThanOrEqualTo(Byte value) {
            addCriterion("adult <=", value, "adult");
            return (Criteria) this;
        }

        public Criteria andAdultIn(List<Byte> values) {
            addCriterion("adult in", values, "adult");
            return (Criteria) this;
        }

        public Criteria andAdultNotIn(List<Byte> values) {
            addCriterion("adult not in", values, "adult");
            return (Criteria) this;
        }

        public Criteria andAdultBetween(Byte value1, Byte value2) {
            addCriterion("adult between", value1, value2, "adult");
            return (Criteria) this;
        }

        public Criteria andAdultNotBetween(Byte value1, Byte value2) {
            addCriterion("adult not between", value1, value2, "adult");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andExpIsNull() {
            addCriterion("exp is null");
            return (Criteria) this;
        }

        public Criteria andExpIsNotNull() {
            addCriterion("exp is not null");
            return (Criteria) this;
        }

        public Criteria andExpEqualTo(Integer value) {
            addCriterion("exp =", value, "exp");
            return (Criteria) this;
        }

        public Criteria andExpNotEqualTo(Integer value) {
            addCriterion("exp <>", value, "exp");
            return (Criteria) this;
        }

        public Criteria andExpGreaterThan(Integer value) {
            addCriterion("exp >", value, "exp");
            return (Criteria) this;
        }

        public Criteria andExpGreaterThanOrEqualTo(Integer value) {
            addCriterion("exp >=", value, "exp");
            return (Criteria) this;
        }

        public Criteria andExpLessThan(Integer value) {
            addCriterion("exp <", value, "exp");
            return (Criteria) this;
        }

        public Criteria andExpLessThanOrEqualTo(Integer value) {
            addCriterion("exp <=", value, "exp");
            return (Criteria) this;
        }

        public Criteria andExpIn(List<Integer> values) {
            addCriterion("exp in", values, "exp");
            return (Criteria) this;
        }

        public Criteria andExpNotIn(List<Integer> values) {
            addCriterion("exp not in", values, "exp");
            return (Criteria) this;
        }

        public Criteria andExpBetween(Integer value1, Integer value2) {
            addCriterion("exp between", value1, value2, "exp");
            return (Criteria) this;
        }

        public Criteria andExpNotBetween(Integer value1, Integer value2) {
            addCriterion("exp not between", value1, value2, "exp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_role
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}