package com.icday.database.automatic.entitys;

import java.util.Date;

public class TbRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.insId
     *
     * @mbggenerated
     */
    private String insid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.cfgid
     *
     * @mbggenerated
     */
    private String cfgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.map
     *
     * @mbggenerated
     */
    private Integer map;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.posX
     *
     * @mbggenerated
     */
    private Double posx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.posY
     *
     * @mbggenerated
     */
    private Double posy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.adult
     *
     * @mbggenerated
     */
    private Byte adult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.exp
     *
     * @mbggenerated
     */
    private Integer exp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.insId
     *
     * @return the value of tb_role.insId
     *
     * @mbggenerated
     */
    public String getInsid() {
        return insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.insId
     *
     * @param insid the value for tb_role.insId
     *
     * @mbggenerated
     */
    public void setInsid(String insid) {
        this.insid = insid == null ? null : insid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.name
     *
     * @return the value of tb_role.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.name
     *
     * @param name the value for tb_role.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.cfgid
     *
     * @return the value of tb_role.cfgid
     *
     * @mbggenerated
     */
    public String getCfgid() {
        return cfgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.cfgid
     *
     * @param cfgid the value for tb_role.cfgid
     *
     * @mbggenerated
     */
    public void setCfgid(String cfgid) {
        this.cfgid = cfgid == null ? null : cfgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.map
     *
     * @return the value of tb_role.map
     *
     * @mbggenerated
     */
    public Integer getMap() {
        return map;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.map
     *
     * @param map the value for tb_role.map
     *
     * @mbggenerated
     */
    public void setMap(Integer map) {
        this.map = map;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.posX
     *
     * @return the value of tb_role.posX
     *
     * @mbggenerated
     */
    public Double getPosx() {
        return posx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.posX
     *
     * @param posx the value for tb_role.posX
     *
     * @mbggenerated
     */
    public void setPosx(Double posx) {
        this.posx = posx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.posY
     *
     * @return the value of tb_role.posY
     *
     * @mbggenerated
     */
    public Double getPosy() {
        return posy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.posY
     *
     * @param posy the value for tb_role.posY
     *
     * @mbggenerated
     */
    public void setPosy(Double posy) {
        this.posy = posy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.createtime
     *
     * @return the value of tb_role.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.createtime
     *
     * @param createtime the value for tb_role.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.adult
     *
     * @return the value of tb_role.adult
     *
     * @mbggenerated
     */
    public Byte getAdult() {
        return adult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.adult
     *
     * @param adult the value for tb_role.adult
     *
     * @mbggenerated
     */
    public void setAdult(Byte adult) {
        this.adult = adult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.level
     *
     * @return the value of tb_role.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.level
     *
     * @param level the value for tb_role.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.exp
     *
     * @return the value of tb_role.exp
     *
     * @mbggenerated
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.exp
     *
     * @param exp the value for tb_role.exp
     *
     * @mbggenerated
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }
}