package com.icday.database.automatic.entitys;

public class TbUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.insId
     *
     * @mbggenerated
     */
    private String insid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.adult
     *
     * @mbggenerated
     */
    private Integer adult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.platform
     *
     * @mbggenerated
     */
    private Integer platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.rolelist
     *
     * @mbggenerated
     */
    private String rolelist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.insId
     *
     * @return the value of tb_user.insId
     *
     * @mbggenerated
     */
    public String getInsid() {
        return insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.insId
     *
     * @param insid the value for tb_user.insId
     *
     * @mbggenerated
     */
    public void setInsid(String insid) {
        this.insid = insid == null ? null : insid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.username
     *
     * @return the value of tb_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.username
     *
     * @param username the value for tb_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.name
     *
     * @return the value of tb_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.name
     *
     * @param name the value for tb_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.adult
     *
     * @return the value of tb_user.adult
     *
     * @mbggenerated
     */
    public Integer getAdult() {
        return adult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.adult
     *
     * @param adult the value for tb_user.adult
     *
     * @mbggenerated
     */
    public void setAdult(Integer adult) {
        this.adult = adult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.platform
     *
     * @return the value of tb_user.platform
     *
     * @mbggenerated
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.platform
     *
     * @param platform the value for tb_user.platform
     *
     * @mbggenerated
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.rolelist
     *
     * @return the value of tb_user.rolelist
     *
     * @mbggenerated
     */
    public String getRolelist() {
        return rolelist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.rolelist
     *
     * @param rolelist the value for tb_user.rolelist
     *
     * @mbggenerated
     */
    public void setRolelist(String rolelist) {
        this.rolelist = rolelist == null ? null : rolelist.trim();
    }
}