package com.icday.database.automatic.mappers;

import com.icday.database.automatic.entitys.TbConfig;
import com.icday.database.automatic.entitys.TbConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_config
     *
     * @mbggenerated
     */
    int countByExample(TbConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_config
     *
     * @mbggenerated
     */
    int deleteByExample(TbConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_config
     *
     * @mbggenerated
     */
    int insert(TbConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_config
     *
     * @mbggenerated
     */
    int insertSelective(TbConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_config
     *
     * @mbggenerated
     */
    List<TbConfig> selectByExample(TbConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbConfig record, @Param("example") TbConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbConfig record, @Param("example") TbConfigExample example);
}