package com.icday.database.automatic.mappers;

import com.icday.database.automatic.entitys.TbPack;
import com.icday.database.automatic.entitys.TbPackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbPackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pack
     *
     * @mbggenerated
     */
    int countByExample(TbPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pack
     *
     * @mbggenerated
     */
    int deleteByExample(TbPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pack
     *
     * @mbggenerated
     */
    int insert(TbPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pack
     *
     * @mbggenerated
     */
    int insertSelective(TbPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pack
     *
     * @mbggenerated
     */
    List<TbPack> selectByExampleWithBLOBs(TbPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pack
     *
     * @mbggenerated
     */
    List<TbPack> selectByExample(TbPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pack
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbPack record, @Param("example") TbPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pack
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TbPack record, @Param("example") TbPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pack
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbPack record, @Param("example") TbPackExample example);
}